name: Java CI
on: [push]
jobs:
  build-BackEnd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B -U -f esieaBack/pom.xml compile
      - name: Run tests and collect coverage
        run: mvn -B -f esieaBack/pom.xml test --fail-never
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          root_dir: esieaBack
          fail_ci_if_error: true

  build-FrontEnd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B -U -f esieaFront/pom.xml compile
