name: Java CI
on: [push]
jobs:
  build-BackEnd:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: stockcar
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'USE stockcar; CREATE TABLE voiture (id integer primary key auto_increment,	marque varchar(30) not null, modele varchar(30) not null, finition varchar(30) not null, carburant char, km integer, annee integer, prix integer); insert into voiture (marque, modele, finition, carburant, km, annee, prix) values ("Citroen", "C4 Picasso", "Feel", "D", 78000, 2017, 15500);' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B -U -f esieaBack/pom.xml compile
      - name: Run tests and collect coverage
        run: mvn -B -f esieaBack/pom.xml test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          root_dir: esieaBack
          fail_ci_if_error: true

  build-FrontEnd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B -U -f esieaFront/pom.xml compile
